version: '3'
services:
  webpacker:
    build: .
    command:  bash -c " yarn && bundle exec bin/webpack-dev-server "
    volumes:
      - .:/copyflix
    ports:
      - "3035:3035"

  db:
    image: postgres
    container_name: db-copyflix
    hostname: db-copyflix
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    container_name: copyflix-web
    hostname: copyflix-web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/copyflix
    ports:
      - "3000:3000"
    depends_on:
      - webpacker
      - db



volumes:
  postgres: